version: '3'
name: bfd-event-bot
services:
  bot:
    image: "node:16"
    user: "node"
    working_dir: "/home/node/bot"
    restart: on-failure:10
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/bot
    command: >
      bash -c "node -v && npm run build && npm run migrate && npm start"
