version: '3'
name: bfd-event-bot-dev
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bfd-event-bot
      MYSQL_USER: bfd-event-bot
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    command: --authentication-policy=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 300s
      retries: 60

  devenv:
    build:
      context: ./docker/development/devenv
      args:
        DOCKER_HOST_UID: ${DOCKER_HOST_UID:?Missing DOCKER_HOST_UID}
        DOCKER_HOST_GID: ${DOCKER_HOST_GID:?Missing DOCKER_HOST_GID}
    ports:
      - "${DEVENV_SSH_PORT:?Missing DEVENV_SSH_PORT}:22"
    volumes:
      - ./:/home/ubuntu/app
      - ~/.ssh:/home/ubuntu/.ssh
      - vscode-remote:/home/ubuntu/.vscode-remote
      - vscode-server:/home/ubuntu/.vscode-server
      - jetbrains-data:/home/ubuntu/.cache/JetBrains

volumes:
  mysql: {}
  vscode-remote: {}
  vscode-server: {}
  jetbrains-data: {}
